### ISSUE TITLE
When building the c++ driver I get the following error. Any idea why that could be?

### ISSUE THREAD

**Issue by bnlerner** [2b-t/myactuator_rmd#5]
```bash
.../myactuator_rmd/src/can/utilities.cpp:11:29: error: 'const struct can_frame' has no member named 'len'
```

**Comment by 2b-t** [comment]
What operating system and kernel are you using?
Can you check the contents of linux/can.h and see what the structure can_frame looks like? I think in older versions len used to be called can_dlc but this is now deprecated in favour of len (see [here](https://github.com/linux-can/can-utils/blob/30a46d72bdacfdccf4686941228c0639cf8ebe89/include/linux/can.h#L122:L129)). If that is true then you could try to modify [this line](https://github.com/2b-t/myactuator_rmd/blob/e4f424809df99912ca776f81a8cee4905fb00cc5/src/can/utilities.cpp#L11) to use can_dlc instead of len.

**Comment by bnlerner** [comment]
Thanks that worked! I'm using 20.04.6
