### ISSUE TITLE
Constants for the X8-Pro-H V3 actuator

### ISSUE THREAD

**Issue by ioio2995** [2b-t/myactuator_rmd#6]
Hello,

I noticed a small inconsistency regarding the constants of the X8-Pro-H V3 motor, which seems very low to me. In the X8ProHV3 class, the torque constant of 0.29 Nm/A probably corresponds to the motor torque without a reducer.

 The technical specifications also specify "motor" for this value,
![Capture d'écran 2024-06-09 193417](https://github.com/2b-t/myactuator_rmd/assets/48251459/0decab95-4154-4ee5-945b-071b4fef153b)
 while for the X8ProV2, the torque of 2.6 Nm/A is expressed without "motor". 
![Capture d'écran 2024-06-09 194707](https://github.com/2b-t/myactuator_rmd/assets/48251459/e3a357fa-0fa7-498e-9655-ebabd7331009)
This change in reference also seems to apply to the entire V3 range. 

What do you think?

Best regards,

**Comment by 2b-t** [comment]
I agree with you. I am generally not sure how much to trust the values that MyActuator provides in their technical specifications. Some of the torque constants seem off (in particular between the 'old' models and their new counterparts, see [here](https://www.myactuator.com/downloads-x-series)). I therefore **calculated the torque constants from the rated torque and the rated current** (see [Wikipedia](https://en.wikipedia.org/wiki/Motor_constants#Motor_torque_constant) and my code [here](https://github.com/2b-t/myactuator_rmd/blob/main/include/myactuator_rmd/actuator_constants.hpp)). In case of the X8-Pro-H V3 you can see [here](https://github.com/2b-t/myactuator_rmd/blob/3f0577accf964fcb223d7da444458c1a85d39ce4/include/myactuator_rmd/actuator_constants.hpp#L297) that this results in 2.13 Nm/A instead of the value given by the manufacturer which is 0.30 Nm/A.
What is even worse are the motor inertias. The rotor inertias are sometimes off by a factor of 10 or so. For example the [X8-25](https://www.myactuator.com/x8-25-details) should be identical to the [X8 Pro V2](https://www.myactuator.com/product-page/x8-pro-1-9). The inertia is though largely different with 30.6 kg cm² vs 3.4 kg cm² while the rest of the specifications are pretty much identical. I noted that the actuators' origins in the CAD drawings are far away from the geometric center. My assumption is that they calculated the inertias to these offset coordinates rather than its center of mass (see [parallel axis theorem](https://en.wikipedia.org/wiki/Parallel_axis_theorem)).

**Comment by ioio2995** [comment]
You are right, my myactuator_rmd repository was behind by two commits. I will make sure to pay more attention to the version of my code next time.

**Comment by 2b-t** [comment]
No worries. It was indeed a mistake that also found its way into my code until recently...
Thanks for confirming my suspicion...
