### ISSUE TITLE
Python bindings usage fails

### ISSUE THREAD

**Issue by TheWylieStCoyote** [2b-t/myactuator_rmd#7]
The python bindings fail when creating new driver.

```
Python 3.12.3 (main, June 19 2024, 05:33:47) [GCC 13.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import myactuator_rmd_py as myactuator_rmd

In [2]: driver1 = myactuator_rmd.Driver('can0', 1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 driver1 = myactuator_rmd.Driver('can0', 1)

TypeError: myactuator_rmd_py.Driver: No constructor defined!

In [3]: dir(myactuator_rmd)
Out[3]: 
['ActuatorException',
 'ActuatorInterface',
 'CanDriver',
 'Driver',
 'ProtocolException',
 'ValueRangeException',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'actuator_constants',
 'actuator_state',
 'can']
```

**Comment by 2b-t** [comment]
Are you using the most up to date version of the code?
The syntax in the latest version should be as follows:

```python3
import myactuator_rmd_py as rmd

driver = rmd.CanDriver("can0")
actuator = rmd.ActuatorInterface(driver, 1)
```
See the [main read-me](https://github.com/2b-t/myactuator_rmd?tab=readme-ov-file#3-using-the-python-bindings).

**Comment by TheWylieStCoyote** [comment]
I pulled in the most newest. Where should I go?

**Comment by 2b-t** [comment]
The latest is perfectly fine but as said you are not running the right commands.
As said try the following:

```python3
import myactuator_rmd_py as rmd

driver = rmd.CanDriver("can0")
actuator = rmd.ActuatorInterface(driver, 1)
```

**Comment by 2b-t** [comment]
_Hi @TheWylieStCoyote,_
Did this resolve your issue?

**Comment by TheWylieStCoyote** [comment]
Yes but, it ended up being a miss configured Python path problem is what I was having. When I would go to import myactuator_rmd_py it was returning the bindings for the old version. However now I am getting a SocketExecption: Interface 'can0' - Could not read CAN frame: Resource temporarily unavailable when ever I'm trying to communicate with the motors.

**Comment by 2b-t** [comment]
Pretty certain that this is not related to this driver but instead a misconfiguration of the communication. The three reasons that I can think of off the top of my head:
- Your CAN interface might not be set up correctly: Verify by running `$ ifconfig` if the interface is up and its name is indeed `can0`. Otherwise you might have set it to up as described in the [`Setup.md` read-me in the `doc/` folder](https://github.com/2b-t/myactuator_rmd/blob/main/doc/Setup.md#2-testing-the-actuator).
- Your actuator might be in a fault state: Try to send it a command through the command line with `cansend` (e.g. `$ cansend can0 141#a400f401a08c0000`, for more details see [the very same read-me](https://github.com/2b-t/myactuator_rmd/blob/main/doc/Setup.md#2-testing-the-actuator)). If this fails power cycle the actuator and try again.
- I had a problem once where the actuator would report a `myactuator_rmd::can::ControllerProblemError` and I had to reset the CAN communication by connecting over UART with their Windows GUI and resetting the CAN communication as described [in this post](https://github.com/2b-t/myactuator_rmd_ros/pull/4#issuecomment-2166969842).

**Comment by 2b-t** [comment]
Any updates on this @TheWylieStCoyote?

**Comment by TheWylieStCoyote** [comment]
Seems like I had a defective CAN Bus controller. When I get a replacement I will re-attack. 

Thanks for your help
